.TH LANDSAT 1 2014-05-25 GNU "Landsat 7 Data Correlation Project Manual"
.SH NAME
landsat \- Correlate data from Landsat 7
.SH SYNOPSIS
.B landsat
.I red_tiff
.I near_infrared_tiff
.SH DESCRIPTION
.B landsat
Reads data from files containing TIFF data taken from landsat 7 and attempts
to correlate the data in different blocks. The output from the program is
printed to stdout.
.SH "SEE ALSO"
.B libtiff (3)
